# Generated by Django 4.2.1 on 2023-08-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "world_cities",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "world_stations",
            },
        ),
        migrations.CreateModel(
            name="CurrentWeather",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="test_app.city",
                    ),
                ),
                ("calendar_date", models.DateField()),
                ("temperature", models.IntegerField()),
                ("feels_like", models.IntegerField()),
                ("weather_condition", models.CharField(max_length=30)),
                ("pressure", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("wind_speed", models.IntegerField()),
                ("wind_direction", models.IntegerField()),
                ("sunrise", models.TimeField()),
                ("sunset", models.TimeField()),
            ],
            options={
                "db_table": "current_weather",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="nearest_station",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="test_app.station",
            ),
        ),
    ]
