# Generated by Django 4.2.1 on 2023-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentweather',
            old_name='city',
            new_name='city_id',
        ),
    ]
