# Generated by Django 4.2.1 on 2023-08-01 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_alter_city_nearest_station"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"managed": True},
        ),
    ]
